### PR TITLE
feat: mercado payment processor

### PR DESCRIPTION
**Pull request by rmagon**
**What is completed:**
1. Initial integration with Mercado API (Token, Save User, Save Card, Refund, Get Cards, Payment with saved card etc.)
1. Generate Mercado tokens
1. Mercado integration backend
1. Store Mercado user and get saved card
1. Basic UI page for accepting card details (both new and saved card in shop mobile but only for order info takeaway page)
1. Refund payment integration with shop mobile

_Demo video: Pay with a new card_ 
https://www.loom.com/share/6e69efad22c740d5a3a6e1596f4458d3

_Demo video: Pay with an existing card_
https://www.loom.com/share/e1fc6b77eb594d9dab52eb7daba4ca8e

**Enhancements/fixes remaining in payment:**
1. Add Mercado payment in other components in shop-mobile
1. Add appropriate loaders
1. Ask for email only if user email doesn’t exist
1. Refund not based on env variable but based on order.stripeId and order.mercadoId
1. Response error handling when the user enters invalid card etc.
1. Check stripe happy flow to make sure there are no regressions
1. Remove stripe option from admin based on env variable
1. Add translations
1. UI Improvements & validations

**Other Issues to check**
1. Check what’s the issue with env variable not updating
1. The main page doesn't always load sometimes needs refresh
1. Refund sometimes fails weirdly

### CODE REVIEW

**Comment by morggansoft** [comment]
Other things to check:
- UI design
- show interaction when there's an existing CC but the user wants to use a new one
- How the interface will interact when these features are implemented https://github.com/ever-co/feature-requests/issues/35 & https://morggan.atlassian.net/jira/software/projects/MF/boards/3?selectedIssue=MF-3
- Database history of payments (successful and failed), and reports

Things to test when finishing up:
- Test CC networks with dummy cards: Master, Visa, Amex
- Test for each CC network all possible error codes

**Comment by rmagon** [comment]
@morggansoft Please find the videos of the different apps & different payment use cases

**Merchant App** 
https://www.loom.com/share/8a6f4b12267a4cf4a31b965bc1a52470

**Admin App** 
https://www.loom.com/share/1936ce1b623444e78bf30aed015c66b9

**Shop mobile existing user:** 
https://www.loom.com/share/7e33b6bcf8414433abbf8f7c1f838453

**Shop mobile new user:** 
https://www.loom.com/share/44b075973967415991ec9ad7343d889f

**Shop mobile refunds:** 
https://www.loom.com/share/805b312d67ed4798a35e89db1109bcec 

The PR is mostly ready 😄I just need to review the code once, refactor if required, and test a little more.

**Comment by rmagon** [comment]
Please add the following environment variables for the Mercado payment integration here:

_admin-web-angular/.env_:
```
MERCADO_PAYMENT=true
```
---

_merchant-tablet-ionic/.env_:
```
MERCADO_PAYMENT=true
```
---

_shop-mobile-ionic/.env_:
```
MERCADO_PUBLISHABLE_KEY=TEST-12d2d7a9-8add-491f-a9d2-c21c7c502f91
```
---

_core/.env_:
```
MERCADO_SECRET_KEY=TEST-7998486328950030-042215-b08075a40f6bc2d90edeb5b6fdbd656f-553274383
```

**Comment by morggansoft** [comment]
Hi Rachit,

To start: awesome job!

Some feedback/questions:

Administration
-------
In merchant:settings:settings or admin:store:manage:payment we saw you've hidden Stripe. We would also like to hide PayPal as to-be-defined in https://morggan.atlassian.net/jira/software/projects/MF/boards/3?selectedIssue=MF-3 We also would like to change de logo, instead of showing the official "mercado" logo we would like to show this logo: https://drive.google.com/file/d/1XpPYzfAgF1zTUesyhyoQCiv5x0UKK6T4/view

Does the selected currency affect in any way the mercado gateway functioning? Or is it a cosmetic text to show prices with a symbol? Maybe it is a good idea to add "UYU" currency which has the same symbol as USD, which is "$".

Publishable key and Secret key are the given by mercado from the mercado account we create?

Shopping experience
------
It is not clear how the cash and card options work together... what happens if a customer has cards but wants to pay cash?

Previously to fill in the cardholder name you can see a faded example saying "John Doe", is that text something you came up with or taken from a variable of the Ever platform? In either case, could it be a field in the json translation files so we can configure it for the Spanish language and be able to change it from there?

Is the email user registration feature something for mercado? or is it a platoform wide community feature that works this way with any payment processor (Stripe, PayPal)? Is there any email validation feature in the roadmap? Are there any other user validation features also as networks (Google, Facebook)?

---
If you are able to show some more videos as you mentioned in Slack we will sure come with more feedback/questions before you finish merging to pull/1 and before we start our own testing, where we will surely have at least a few more questions.

**Comment by rmagon** [comment]
Thank you so much!

I have changed the logo and removed Paypal from the options, please find the screenshots below:

1. `merchant:settings:settings`
Screenshot 2020-05-08 at 7 18 00 PM
Screenshot 2020-05-08 at 7 18 13 PM
Screenshot 2020-05-08 at 7 18 20 PM

2. `admin:store:manage:payment`
Screenshot 2020-05-08 at 7 41 59 PM

--

To answer your questions: 

`1. Does the selected currency affect in any way the Mercado gateway functioning?`
The selected currency, pay button text, and keys are currently only stored in the database and do not affect functioning in any way. As of now, this is the same for Stripe, Paypal and hence I've just implemented it in a similar way. When we support multi-currency (will have to check with Ruslan on the roadmap) with Stripe/Paypal in the system it can also be added to Mercado as a small enhancement. 

`2. Publishable key and Secret key are the given by Mercado from the Mercado account we create?`
Yes as described in https://github.com/morggansoft/tuPedido/pull/1#issuecomment-625435970 we can give `MERCADO_SECRET_KEY` and `MERCADO_PUBLISHABLE_KEY` in the respective **env files** to use your own Mercado account. (Please note that there are 'Secret Key' and 'Public Key' options in `merchant:settings:settings` and `admin:store:manage:payment` but they are not supported by the payment implementation currently but just stored, same as 1. above, when they are implemented for Paypal/Stripe we can add them for Mercado too with the same  enhancement as 1)

`3. It is not clear how the cash and card options work together... what happens if a customer has cards but wants to pay cash?`
By default, payments are 'cash' and customers have the option to pay by card. I guess we can discuss more of this on Slack with Ruslan to see if we want some changes to this flow

`4. Previously to fill in the cardholder name you can see a faded example saying "John Doe",`
I've added most of the translations in en-US.json (including John Doe `PAYMENT.PLACEHOLDER.NAME` ), they can be controlled from there 😄 

`5. Is the email user registration feature something for Mercado? or is it a platform-wide community feature that works this way with any payment processor`
Email is required by Stripe as well as Mercado and also stored in our User object in the email field. 
There is a social sign-in (eg: with Gmail) option which I suppose in the roadmap currently, once that works then we wouldn't have to enter the email field (there wouldn't be any need of code change from the Mercado integration side, the 'email' field only shows up if the user object doesn't have an email address.

**Comment by morggansoft** [comment]
Merge pull 1 Ok

**Comment by morggansoft** [comment]
Hi Rachit!

Thanks for the advances!

Could you mention anything on this?:
> * Database history of payments (successful and failed), and reports

**Pull request merged**
